"""Read-only independent stored-field replay of four E2 fixed equations."""
from pathlib import Path
from fractions import Fraction as Q
import hashlib,importlib.util,json,math,struct,sys
import mpmath as mp
P=Path(__file__).resolve().parent;ROOT=P.parents[1]
def require(ok,message):
 if not ok:raise ValueError(message)
def module(name,path):
 s=importlib.util.spec_from_file_location(name,path);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
a=module('frozen_equation_oracle',ROOT/'evidence/forcing-e1-fixed-candidates-v1/analyze.py');scalar=module('independent_H_oracle',P/'check_scalar.py')
def records(path):return [json.loads(x)for x in path.read_text().splitlines()if x.startswith('{')]
def bits(x):return struct.pack('>d',x)
def run(dps):
 mp.mp.dps=dps;policy=json.loads((P/'protocol.json').read_text());packet=json.loads((P/'inputs.json').read_text());data=records(P/'candidate-fixed.log');baseline=records(P/'baseline-reproduced.log');require('1 passed; 0 failed'in(P/'candidate-fixed.log').read_text()and not(P/'candidate-fixed-stderr.log').read_bytes(),'actual assertions pass without controller trace');require([x for x in(P/'baseline-reproduced.log').read_bytes().splitlines()if x.startswith(b'{')]==[x for x in(ROOT/'evidence/forcing-e1-fixed-candidates-v1/capture-native.log').read_bytes().splitlines()if x.startswith(b'{')],'baseline exact numerical JSON bytes')
 complete=[x for x in data if x['event']=='fixed_capture_complete'];require([x['index']for x in complete]==[41,47]and all(x['mode']=='E2'and x['owner_advances']==x['controller_iterations']==0 and x['equation_evaluations']==2 and not x['published']for x in complete),'exact roster with no owner or controller')
 outcomes=[];gates=[]
 for c in packet['cases']:
  c=dict(c,acceleration=[.0625,-.125,.03125]if c['load']=='forward'else[-.0625,.125,-.03125])
  for order in [16,32]:
   events=[x for x in data if x['event']in['fixed_equation','fixed_equation_refusal']and x['index']==c['index']and x['order']==order];require(len(events)==1,'one actual fixed equation outcome');eq=events[0];require(eq['mode']=='E2'and eq['owner_advances']==0 and not eq['published'],'actual fixed scope')
   if eq['event']=='fixed_equation_refusal':outcomes.append({'index':c['index'],'order':order,'status':'NATIVE_EQUATION_REFUSAL','error':eq['error'],'native_acceptance':False});continue
   original=next(x for x in baseline if x['event']=='fixed_equation'and x['index']==c['index']and x['order']==order);points=[x for x in data if x['event']=='fixed_point'and x['index']==c['index']and x['order']==order];start=next(x for x in points if x['label']=='start');end=next(x for x in points if x['label']=='end');quad=[x for x in points if x['label']=='quadrature'];partition=next(x for x in data if x['event']=='fixed_partition'and x['index']==c['index']and x['order']==order)['partition'];require(len(quad)==order*(len(partition)-1)<=65*order,'complete actual changed-path quadrature')
   rate,rounded=a.native(c,eq);direct,_=a.native(c,eq,True);require(all(bits(x)==bits(y)for x,y in zip(rate,eq['rate']))and all(bits(x)==bits(y)for x,y in zip(direct,eq['direct_rate']))and bits(math.sqrt(a.sequential(x*x for x in rate)))==bits(eq['norm']),'bit-exact whole native equation uses actual stored difference, not deltaL')
   force,_,_=a.forces(c,end,end['velocity'],False);plus,minus=a.transfers(quad,len(eq['pairs']),False);require(all(bits(x)==bits(y)for u,v in zip(force,eq['end_force'])for x,y in zip(u,v))and all(bits(x)==bits(y)for u,v in [(plus,eq['plus']),(minus,eq['minus'])]for x,y in zip(u,v)),'fresh changed-candidate native force and transfer replay')
   known_errors=[]
   for point in points:
    time=point['time'];native_eta=[c['eta'][i]+time*c['final_authorized_unknowns'][i]for i in range(6)];native_q=[(c['q'][i]+time*c['eta'][i])+((.5*time)*time)*c['final_authorized_unknowns'][i]for i in range(3)];require(all(bits(x)==bits(y)for x,y in zip(point['eta'],native_eta))and all(bits(x)==bits(y)for x,y in zip(point['q'],native_q)),'native public-known and geometry graph retained at every actual time')
    for k,j in enumerate(a.KNOWN):
     sign=-1 if k==6 else 1;coord=a.COORD[k];require(bits(point['z'][j])==bits(sign*native_eta[coord]),'stored knowns are native public values');product=scalar.rounded(Q(time)*Q(c['final_authorized_unknowns'][coord]));require(product is not None,'observed working product normal');working=scalar.rounded(Q(c['eta'][coord])+scalar.value(product));require(working is not None,'observed working affine normal');expected=sign*scalar.value(working);actual=scalar.value(point['chart_endpoint_parts'][j]);require(actual==expected,'actual H affine known parts agree with independent per-operation oracle');known_errors.append(float(Q(point['z'][j])-actual))
   exact,groups=a.exact(c,eq);exact_direct,_=a.exact(c,eq,direct=True);latent=tuple(scalar.value(x)for x in end['chart_endpoint_parts']);stored=tuple(Q(x)for x in eq['end_z']);rho=tuple(x-y for x,y in zip(stored,latent));latent_vector,_=a.exact(c,eq,z=latent);rho_projected=[Q(0)]*22
   for i in range(16):
    for d in range(2):
     contribution=Q(eq['end_mass'][i])*sum(Q(w)*v for w,v in zip(eq['r'][i][d],rho))/Q(c['h'])
     for j in range(22):rho_projected[j]+=Q(eq['r'][i][d][j])*contribution
   require([x-y for x,y in zip(exact,latent_vector)]==rho_projected,'complete exact reconciliation rho accounted; stored versus latent equation differs')
   embedded0=a.embedding(eq,list(map(Q,eq['start_z'])));embedded1=a.embedding(eq,list(map(Q,eq['end_z'])));defect=[Q(0)]*22
   for i in range(16):
    for d in range(2):
     value=Q(eq['end_mass'][i])*((embedded1[i][d]-Q(eq['end_velocity'][i][d]))-(embedded0[i][d]-Q(c['accepted_publication']['velocity'][i][d])))/Q(c['h'])
     for j in range(22):defect[j]+=Q(eq['r'][i][d][j])*value
   require([x-y for x,y in zip(exact,exact_direct)]==defect,'exact stored stable/direct embedding identity retained')
   changes={k:sum(bits(x)!=bits(y)for x,y in zip(eq[k],original[k]))for k in ['end_z','end_q','end_eta','end_mass','plus','minus']};require(changes['end_q']==changes['end_eta']==changes['end_mass']==0,'unchanged public endpoint geometry/knowns/mass');require(all(bits(eq['end_z'][j])==bits(original['end_z'][j])for j in a.KNOWN),'all public known endpoint bits unchanged')
   matrix=tuple(tuple(x)for x in end['d']);actual_chart=a.chart(matrix,tuple(latent[j]for j in a.KNOWN));continuous=tuple((-1 if k==6 else 1)*(Q(c['eta'][a.COORD[k]])+Q(c['h'])*Q(c['final_authorized_unknowns'][a.COORD[k]]))for k in range(7));continuous_chart=a.chart(matrix,continuous);stored_chart=a.chart(matrix,tuple(stored[j]for j in a.KNOWN))
   outcomes.append({'index':c['index'],'order':order,'status':'NATIVE_FIXED_EQUATION_EVALUATED','h':c['h'],'native_norm':eq['norm'],'native_direct_norm':eq['direct_norm'],'original_E1_norm':original['norm'],'native_newton_target':1e-13,'native_newton_eligible':eq['norm']<=1e-13,'signed_native_target_margin':1e-13-eq['norm'],'native_rate_components':eq['rate'],'native_direct_components':eq['direct_rate'],'exact_stored_stable':a.summarize(exact,'Exact complete stored-field equation on actual E2 binary inputs; diagnostic only.'),'exact_stored_direct':a.summarize(exact_direct,'Exact complete direct equation on actual stored nodal endpoint; diagnostic only.'),'latent_inertia_only_counterfactual':a.summarize(latent_vector,'Isolated latent inertia on captured E2 forces/donors; not an acceptance candidate.'),'rho_projected_over_h':a.summarize(rho_projected,'Exact reconciliation contribution in reduced momentum-rate units.'),'rho_exact_components':[str(x)for x in rho],'rho_max':float(max(map(abs,rho))),'actual_H_vs_exact_actual_H_known_chart_max_gap':float(max(abs(x-y)for x,y in zip(latent,actual_chart))),'actual_H_vs_exact_continuous_chart_max_gap':float(max(abs(x-y)for x,y in zip(latent,continuous_chart))),'actual_H_vs_exact_stored_known_chart_max_gap':float(max(abs(x-y)for x,y in zip(latent,stored_chart))),'exact_stored_constraint_max':float(max(abs(sum(Q(d)*z for d,z in zip(row,stored)))for row in end['d'])),'maximum_known_public_vs_working_gap_over_actual_points':max(map(abs,known_errors)),'bit_changes_vs_original_E1':changes,'native_velocity_component_changes':sum(bits(x)!=bits(y)for u,v in zip(eq['end_velocity'],original['end_velocity'])for x,y in zip(u,v)),'native_force_component_changes':sum(bits(x)!=bits(y)for u,v in zip(eq['end_force'],original['end_force'])for x,y in zip(u,v)),'actual_sign_partition':partition,'diagnostic_quadrature_points':len(quad),'maximum_native_constraints':eq['maximum_constraints'],'exact_rho_reconciliation_identity':True,'exact_stored_embedding_defect_identity':True,'public_known_and_geometry_bit_policy_preserved':True,'native_stored_inertia_replayed':True,'fresh_native_force_transfer_replayed':True,'native_acceptance':False,'published':False,'third_solve_executed':False,'term_groups':{k:{'norm':a.normq(v),'components':[float(x)for x in v]}for k,v in groups.items()}})
  reports=[x for x in data if x['event']=='fixed_planar_gates'and x['index']==c['index']];require(len(reports)<=1,'one paired planar qualifier')
  for row in reports:
   require(row['candidate_metadata_only']and row['third_solve_executed']is False and row['owner_advances']==0 and not row['published'],'planar qualifier is not a published step');result=row['result'];entry={'index':c['index'],'native_result':result,'passed':result.startswith('Ok('),'third_solve_executed':False,'public_step_completed':False}
   if entry['passed']:
    report=a.debug_reader.debug(result[3:-1]);require(report['finite_momentum_rate_norm']<=1e-11 and report['direct_momentum_rate_norm']<=1e-11 and report['quadrature_error']<=1e-15 and report['full_constraints']<=1e-11 and abs(report['ledger_error'])<=report['work_allowance']and abs(report['residual_work'])<=report['work_allowance']and abs(report['pressure_work'])<=report['work_allowance']and min(report[k]for k in ['backward_euler_loss','mixing_loss','viscous_loss'])>=0,'all reported original planar gates');entry['report']=report
   gates.append(entry)
 require([(x['index'],x['order'])for x in outcomes]==[(41,16),(41,32),(47,16),(47,32)],'all four actual equation outcomes retained')
 return {'status':'PASS_AUTHORIZED_FIXED_EXPERIMENT_REPLAY_ONLY','precision_digits':dps,'rows':outcomes,'planar_qualifiers':gates,'native_equations_requested':4,'native_equations_evaluated':sum(x['status']=='NATIVE_FIXED_EQUATION_EVALUATED'for x in outcomes),'native_equation_refusals':sum(x['status']=='NATIVE_EQUATION_REFUSAL'for x in outcomes),'native_newton_eligible_equations':sum(x.get('native_newton_eligible',False)for x in outcomes),'original_E1_failures_reproduced':2,'original_runtime_refusals_unresolved':2,'original_geometry_band_failures_unresolved':8,'new_controller_iterations':0,'accepted_owners_constructed':0,'accepted_owners_advanced':0,'new_trajectory_steps':0,'new_reference_integrations':0,'third_solve_executed':False,'published':False,'production_adoption':False,'trajectory_remedy_established':False,'arithmetic_floor_claimed':False,'scope':'Four fixed equations and planar gates; stored endpoint authoritative. Any latent sensitivity is counterfactual. No public call, third solve, accepted state, trajectory or geometry-band qualification.'}
if __name__=='__main__':print(json.dumps(run(int(sys.argv[1])if len(sys.argv)>1 else 80),indent=2,sort_keys=True))
