"""Read two actual native jobs; no native invocation or new reference."""
from pathlib import Path
import copy,hashlib,importlib.util,json,math,struct
P=Path(__file__).resolve().parent;ROOT=P.parents[1]
def require(ok,msg):
 if not ok:raise ValueError(msg)
def sha(b):return hashlib.sha256(b).hexdigest()
def load(name,path):
 s=importlib.util.spec_from_file_location(name,path);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def rows(path):return [json.loads(x)for x in path.read_text().splitlines()if x.startswith('{')]
def bit_tree(x):
 if isinstance(x,float):return ['f64',struct.pack('>d',x).hex()]
 if isinstance(x,list):return [bit_tree(v)for v in x]
 if isinstance(x,dict):return {k:bit_tree(v)for k,v in x.items()}
 return x
def state(row):return {k:row[k]for k in ['velocity','pressure_coefficients','positions','triangles','periodic_indices','mass','time','stamp']}
def validate_success(row,result,trace,previous):
 p=row['report']['planar'];t=row['report']['third'];w=row['report']['total'];require(result['result'].startswith('Ok('),'actual public success');require(row['stamp']=={'id':131,'version':26}and row['step']==26 and row['time']==previous['time']+row['h'],'one actual publication successor');require(row['pressure_coefficients']==row['unknowns'][6:]and row['third_coefficients']==t['coefficients'],'pressure/third publication binding')
 require(result['seen']==[1,1,1,613,1,3,1,1,24,1,1,0],'all reached actual stages');checks=[x for x in trace if x['event']=='newton_check'];corrections=[x for x in trace if x['event']=='correction'];require(len(checks)==3 and len(corrections)==2 and [x['calls']for x in checks]==[1,8,15]and p['iterations']==3 and p['equation_evaluations']==15,'actual ordinary bounded seed/controller');require(all(x['accepted_version']==25 and x['newton_threshold']==1e-13 and x['iteration_limit']==7 for x in checks)and checks[-1]['rate_norm']<=1e-13,'unchanged actual convergence target')
 for r in [p,t]:
  for k in ['finite_momentum_rate_norm','direct_momentum_rate_norm']:require(math.isfinite(r[k])and 0<=r[k]<=1e-11,'original momentum rate gate')
 for r in [p,t,w]:
  require(min(r[k]for k in ['backward_Euler_loss','mixing_loss','viscous_loss'])>=0 and max(abs(r[k])for k in ['energy_ledger_error','discrete_residual_work'])<=r['fixed_work_allowance'],'separate/combined work gates')
 require(p['finite_momentum_rate_norm']<=1e-13 and p['quadrature_error']<=1e-15 and p['full_constraints']<=1e-11 and abs(p['pressure_work'])<=p['fixed_work_allowance'],'original stricter reported planar/quad/constraints gates');require(t['shear_x_loss']>0 and t['shear_y_loss']>0,'both third shears actually exercised');require(max(math.hypot(p[k],t[k])for k in ['finite_momentum_rate_norm','direct_momentum_rate_norm'])<=1e-11,'full three-component rate');require(row['forcing']['acceleration']==[-.0625,.125,-.03125]and row['forcing']['force_count']==1,'original force');require(abs((row['forcing']['planar_work']+row['forcing']['third_work'])-row['forcing']['total_work'])<=w['fixed_work_allowance'],'combined forcing work')
 parsed=load('debug',ROOT/'evidence/forcing-public-call-66k/analyze.py').debug(result['result'][3:-1]);require(parsed['step']['planar']['before']==previous['stamp']and parsed['step']['planar']['after']==row['stamp']and bit_tree(parsed['step']['planar']['unknowns'])==bit_tree(row['unknowns'])and bit_tree(parsed['step']['third']['coefficients'])==bit_tree(row['third_coefficients'])and bit_tree(parsed['forces'])==bit_tree(row['forcing']),'public result and emitted state lineage');return checks,corrections

def run():
 b=json.loads((P/'binary-binding.json').read_text());require(sha(Path(b['binary']).read_bytes())==b['binary_sha256'],'actual ELF');require(b['prototype']=='409c140cb761d267da78d2a8cdac623ff45e9772'and b['prototype_tree']=='34ebbb1c24ad5a3888c96a485ac9ec9da02d5a4d','frozen compiled source');require(b['protocol_sha256']==sha((P/'protocol.json').read_bytes()),'compiled protocol');preflight=json.loads((P/'preflight-receipt.json').read_text());require(preflight==json.loads((P/'preflight-qualified.json').read_text())and preflight['owner_advances']==0 and preflight['memory_bound']==65760,'actual completed preflight before owners');original=rows(ROOT/'evidence/forcing-e1-trajectories-v2/trajectory-47-native.log');original_pubs=[x for x in original if 'model'in x];original_trace=rows(ROOT/'evidence/forcing-e1-trajectories-v2/trajectory-47-native-stderr.log');outputs={};pubs={};traces={}
 for mode in ['E1','E2']:
  cmd=json.loads((P/(mode+'-command-completed.json')).read_text());before=json.loads((P/(mode+'-command-before.json')).read_text());require({k:v for k,v in cmd.items()if k not in ['exit','seconds','stdout_sha256','stderr_sha256']}==before,'actual completed command');require(cmd['argv']==[b['binary'],'--exact','research_public_call::case47_single_public_comparison','--nocapture']and cmd['environment']=={'RHEON_CASE47_PUBLIC_ALLOW':'case47-E1-prefix25-one-call-v1','RHEON_CASE47_MODE':mode}and cmd['prefix_steps']==25 and cmd['comparison_calls']==1 and cmd['exit']==0 and cmd['binary_sha256']==b['binary_sha256']and cmd['preflight_sha256']==sha((P/'preflight-receipt.json').read_bytes()),'exact authorized invocation');require(cmd['stdout_sha256']==sha((P/(mode+'-native.log')).read_bytes())and cmd['stderr_sha256']==sha((P/(mode+'-native-stderr.log')).read_bytes()),'actual journal hashes');require('1 passed; 0 failed'in(P/(mode+'-native.log')).read_text(),'native assertions passed');data=rows(P/(mode+'-native.log'));publications=[x for x in data if 'model'in x];events=[x for x in data if 'event'in x];require([x['event']for x in events]==['case47_begin','case47_prefix_verified','case47_result','case47_complete'],'one job/one comparison');require(bit_tree(publications[:26])==bit_tree(original_pubs),'all constructor and 25 prefix publication/report bits reproduced');require(len(publications)==27,'one comparison journal only');result=events[2];complete=events[3];trace=rows(P/(mode+'-native-stderr.log'));start=next(i for i,x in enumerate(trace)if x['event']=='newton_check'and x['accepted_version']==25);require(trace[:start]==original_trace[:start],'entire original prefix Newton trace reproduced');comparison=trace[start:];outputs[mode]={'result':result['result'],'seen':result['seen'],'accepted_version':complete['accepted_version']};pubs[mode]=publications;traces[mode]=comparison
  if mode=='E1':require(result['result']=='Err(IterationLimit)'and complete['accepted_version']==25 and bit_tree(state(publications[-1]))==bit_tree(state(publications[-2]))and comparison==original_trace[start:start+len(comparison)],'original full E1 refusal and accepted-state bits reproduced')
  else:
   checks,corrections=validate_success(publications[-1],result,comparison,publications[-2]);outputs[mode].update(corrections=len(corrections),checks=len(checks),counted_equations=15,final_acceptance_equations=2,final_Newton_norm=checks[-1]['rate_norm'],report=publications[-1]['report'],forcing=publications[-1]['forcing'],published_time=publications[-1]['time'],full_stable_norm=math.hypot(publications[-1]['report']['planar']['finite_momentum_rate_norm'],publications[-1]['report']['third']['finite_momentum_rate_norm']),full_direct_norm=math.hypot(publications[-1]['report']['planar']['direct_momentum_rate_norm'],publications[-1]['report']['third']['direct_momentum_rate_norm']))
 controls=[]
 row=pubs['E2'][-1];result={'result':outputs['E2']['result'],'seen':outputs['E2']['seen']}
 for name,mutate in [('wrong version',lambda r:r['stamp'].update(version=27)),('wrong pressure',lambda r:r['pressure_coefficients'].__setitem__(0,0.)),('omitted third shear',lambda r:r['report']['third'].update(shear_y_loss=0.)),('false work',lambda r:r['report']['total'].update(energy_ledger_error=1.)),('relaxed planar gate',lambda r:r['report']['planar'].update(finite_momentum_rate_norm=1e-12)),('wrong third publication',lambda r:r['third_coefficients'].__setitem__(0,0.)),('wrong force',lambda r:r['forcing']['acceleration'].__setitem__(2,0.))]:
  bad=copy.deepcopy(row);mutate(bad)
  try:validate_success(bad,result,traces['E2'],pubs['E2'][-2])
  except ValueError:controls.append(name)
  else:raise ValueError('missed corruption '+name)
 return {'status':'PASS_CASE47_SINGLE_FULL_PUBLIC_CALL','native_source':b['prototype'],'native_source_tree':b['prototype_tree'],'binary_sha256':b['binary_sha256'],'preflight_source':'507e6b3c191c94d8ebab414773ab97d41fa21710','jobs':outputs,'native_owners':2,'maximum_simultaneous_owners':1,'historical_prefix_advances':50,'comparison_attempts':2,'E2_accepted_comparison_advances':1,'trajectory_extension':False,'reference_integrations':0,'case41_new_equations':0,'original_runtime_failures_preserved':2,'original_geometry_band_failures_preserved':8,'memory_bound':65760,'memory_cap':67584,'negative_controls':controls,'production_adoption':False,'scope':'One E2 ordinary published extruded call from bit-exact E1 prefix25 versus reproduced E1 refusal. No pure E2 trajectory, cancellation extension or original geometry-band repair.'}
if __name__=='__main__':print(json.dumps(run(),indent=2,sort_keys=True))
