import Rheon
import Lean.Util.CollectAxioms

open Lean Elab Command
run_cmd do
  let env ← getEnv
  let allowed : Array Name := #[`propext, `Classical.choice, `Quot.sound]
  let expected : Array Name := #[
    `Rheon.SphereContact.squared,
    `Rheon.SphereContact.normalSpeed,
    `Rheon.SphereContact.response,
    `Rheon.SphereContact.kinetic,
    `Rheon.SphereContact.squared_trajectory,
    `Rheon.SphereContact.perpendicular_trajectory,
    `Rheon.SphereContact.conditional_quadratic_root,
    `Rheon.SphereContact.quadratic_factorization,
    `Rheon.SphereContact.quadratic_positive_before,
    `Rheon.SphereContact.face_linear_root,
    `Rheon.SphereContact.radial_impulse_zero_torque,
    `Rheon.SphereContact.unit_normal_restitution,
    `Rheon.SphereContact.response_momentum,
    `Rheon.SphereContact.unit_normal_energy_change,
    `Rheon.SphereContact.conditional_energy_nonincrease,

    `Rheon.Discrete.gradient,
    `Rheon.Discrete.incidence,
    `Rheon.Discrete.laplace,
    `Rheon.Discrete.corrected,
    `Rheon.Discrete.adjoint_identity,
    `Rheon.Discrete.pressure_energy,
    `Rheon.Discrete.pressure_nonnegative,
    `Rheon.Discrete.pressure_symmetric,
    `Rheon.Discrete.constant_gradient_zero,
    `Rheon.Discrete.constant_pressure_nullspace,
    `Rheon.Discrete.internal_flux_conservation,
    `Rheon.Discrete.conservative_update,
    `Rheon.Discrete.projection_residual,
    `Rheon.Discrete.exact_projection,
    `Rheon.Indexing.flatten,
    `Rheon.Indexing.flatten_in_bounds,
    `Rheon.Indexing.staggered_count,
    `Rheon.Transport.blend,
    `Rheon.Transport.blend_lower,
    `Rheon.Transport.blend_upper,
    `Rheon.Transport.blend_constant,
    `Rheon.Transport.convex_sum_bounds,
    `Rheon.Transport.upwind_positive,
    `Rheon.Transport.explicit_diffusion_positive,
    `Rheon.Transport.cfl_counterexample,
    `Rheon.Transport.interpolation_not_mass_conservative,
    `Rheon.Physics.force_work_identity,
    `Rheon.Physics.hydrostatic_increment,
    `Rheon.Physics.positive_transmissibility,
    `Rheon.Physics.weighted_pressure_energy,
    `Rheon.Physics.internal_amount_balance,
    `Rheon.Physics.sealed_flux_compatibility,
    `Rheon.Physics.volume_source_balance,
    `Rheon.Physics.weighted_energy_identity,
    `Rheon.Physics.implicit_energy_identity,
    `Rheon.Physics.implicit_energy_nonincrease,
    `Rheon.Physics.slip_power_nonpositive,
    `Rheon.Physics.young_adhesion_identity,
    `Rheon.Physics.adhesion_bounds,
    `Rheon.BoundedPhysics.segment,
    `Rheon.BoundedPhysics.wallValue,
    `Rheon.BoundedPhysics.wallHit,
    `Rheon.BoundedPhysics.wall_segment_affine,
    `Rheon.BoundedPhysics.wall_hit_range,
    `Rheon.BoundedPhysics.wall_hit_on_surface,
    `Rheon.BoundedPhysics.wall_first_hit,
    `Rheon.BoundedPhysics.clipped_segment_in_halfspace,
    `Rheon.BoundedPhysics.strain,
    `Rheon.BoundedPhysics.viscousOperator,
    `Rheon.BoundedPhysics.dissipation,
    `Rheon.BoundedPhysics.viscous_work,
    `Rheon.BoundedPhysics.dissipation_nonnegative,
    `Rheon.BoundedPhysics.backward_euler_work,
    `Rheon.BoundedPhysics.backward_euler_energy_nonincrease,
    `Rheon.WallFriction.wall_force_work,
    `Rheon.WallFriction.common_translation,
    `Rheon.WallFriction.relative_dissipation_nonnegative,
    `Rheon.WallFriction.explicit_work_identity,
    `Rheon.NoSlip.compatible_reaction_preserves_trace,
    `Rheon.NoSlip.relative_reaction_work_zero,
    `Rheon.NoSlip.momentum_balance,
    `Rheon.NoSlip.constrained_work_identity,
    `Rheon.ColumnForcing.units_agree,
    `Rheon.ColumnForcing.reaction_includes_body_force,
    `Rheon.ColumnForcing.forced_momentum,
    `Rheon.ColumnForcing.forced_work,
    `Rheon.ColumnForcing.parabola,
    `Rheon.ColumnForcing.parabola_endpoints,
    `Rheon.ColumnForcing.quadratic_stencil_balance,
    `Rheon.ColumnForcing.recurrence_about_equilibrium,
    `Rheon.StaticObstacle.overlap,
    `Rheon.StaticObstacle.overlap_nonnegative,
    `Rheon.StaticObstacle.overlap_symmetric,
    `Rheon.StaticObstacle.overlap_bounded,
    `Rheon.StaticObstacle.fluidVolume,
    `Rheon.StaticObstacle.fluid_volume_bounds,
    `Rheon.StaticObstacle.shared_flux_cancels,
    `Rheon.StaticObstacle.component_constant_jump_zero,
    `Rheon.StaticObstacle.residual_divergence_scale,
    `Rheon.ObstacleOperators.edgeIncidence,
    `Rheon.ObstacleOperators.edge_gradient,
    `Rheon.ObstacleOperators.edge_balanced,
    `Rheon.ObstacleOperators.outwardFlux,
    `Rheon.ObstacleOperators.pressureWeight,
    `Rheon.ObstacleOperators.faceMass,
    `Rheon.ObstacleOperators.pressureCorrected,
    `Rheon.ObstacleOperators.pressureRhs,
    `Rheon.ObstacleOperators.pressureResidual,
    `Rheon.ObstacleOperators.kineticEnergy,
    `Rheon.ObstacleOperators.kinetic_increment,
    `Rheon.ObstacleOperators.face_mass_coefficient,
    `Rheon.ObstacleOperators.pressure_corrected_flux,
    `Rheon.ObstacleOperators.pressure_flux_residual,
    `Rheon.ObstacleOperators.pressure_divergence_residual,
    `Rheon.ObstacleOperators.component_rhs_compatible,
    `Rheon.ObstacleOperators.pressure_correction_energy,
    `Rheon.ObstacleOperators.exact_pressure_energy_nonincrease,
    `Rheon.ObstacleOperators.shearConductance,
    `Rheon.ObstacleOperators.navierConductance,
    `Rheon.ObstacleOperators.navierTrace,
    `Rheon.ObstacleOperators.shear_conductance_positive,
    `Rheon.ObstacleOperators.navier_conductance_nonnegative,
    `Rheon.ObstacleOperators.navier_free_slip,
    `Rheon.ObstacleOperators.navier_series_traction,
    `Rheon.ObstacleOperators.navier_dissipation_split,
    `Rheon.ObstacleOperators.stationaryWallDiagonal,
    `Rheon.ObstacleOperators.stationary_wall_nonnegative,
    `Rheon.ObstacleOperators.stationary_wall_force,
    `Rheon.ObstacleOperators.shearOperator,
    `Rheon.ObstacleOperators.shearDissipation,
    `Rheon.ObstacleOperators.shear_work,
    `Rheon.ObstacleOperators.shear_dissipation_nonnegative,
    `Rheon.ObstacleOperators.forced_shear_energy,
    `Rheon.ObstacleOperators.forced_shear_momentum,
    `Rheon.ObstacleOperators.two_wall_shear_momentum,
    `Rheon.ObstacleOperators.unforced_shear_energy_nonincrease,
    `Rheon.ObstacleOperators.reducedShearGradient,
    `Rheon.ObstacleOperators.reduced_symmetric_strain_dissipation,
    `Rheon.AlignedStrain.gather,
    `Rheon.AlignedStrain.strainOperator,
    `Rheon.AlignedStrain.strainLoss,
    `Rheon.AlignedStrain.rowAbs,
    `Rheon.AlignedStrain.faceBound,
    `Rheon.AlignedStrain.rowBound,
    `Rheon.AlignedStrain.row_bound_nonnegative,
    `Rheon.AlignedStrain.face_le_row_bound,
    `Rheon.AlignedStrain.forceNorm,
    `Rheon.AlignedStrain.euler,
    `Rheon.AlignedStrain.transpose_work,
    `Rheon.AlignedStrain.loss_nonnegative,
    `Rheon.AlignedStrain.transpose_pairing,
    `Rheon.AlignedStrain.operator_symmetric,
    `Rheon.AlignedStrain.row_abs_nonnegative,
    `Rheon.AlignedStrain.coefficient_le_row_abs,
    `Rheon.AlignedStrain.zero_row_coefficient,
    `Rheon.AlignedStrain.zero_row_gather,
    `Rheon.AlignedStrain.face_cauchy,
    `Rheon.AlignedStrain.coefficient_force_bound,
    `Rheon.AlignedStrain.euler_energy_identity,
    `Rheon.AlignedStrain.euler_energy_nonincrease,
    `Rheon.AlignedStrain.euler_row_bound_nonincrease,
    `Rheon.AlignedStrain.euler_exact_projection_nonincrease,
    `Rheon.AlignedStrain.unit_corner_block,
    `Rheon.AlignedStrain.flat_conductance,
    `Rheon.MeshTraction.dot,
    `Rheon.MeshTraction.cross,
    `Rheon.MeshTraction.add,
    `Rheon.MeshTraction.sub,
    `Rheon.MeshTraction.nodal,
    `Rheon.MeshTraction.conditional_moment_reduction,
    `Rheon.MeshTraction.resultant_closed_form,
    `Rheon.MeshTraction.point_virtual_work,
    `Rheon.MeshTraction.triangle_virtual_work,
    `Rheon.MeshTraction.reference_shift,
    `Rheon.RigidImpulse.kick,
    `Rheon.RigidImpulse.kinetic,
    `Rheon.RigidImpulse.midpoint,
    `Rheon.RigidImpulse.residual,
    `Rheon.RigidImpulse.component_momentum,
    `Rheon.RigidImpulse.component_residual_work,
    `Rheon.RigidImpulse.component_impulse_work,
    `Rheon.RigidImpulse.six_component_impulse_work,
    `Rheon.RigidImpulse.six_component_residual_work,
    `Rheon.RigidImpulse.component_kinetic_nonnegative,
    `Rheon.RigidImpulse.inertia_triangle_inequalities,
    `Rheon.RigidMotion.product,
    `Rheon.RigidMotion.conjugate,
    `Rheon.RigidMotion.normSquared,
    `Rheon.RigidMotion.drift,
    `Rheon.RigidMotion.product_norm,
    `Rheon.RigidMotion.conjugate_norm,
    `Rheon.RigidMotion.conditional_unit_drift,
    `Rheon.RigidMotion.conditional_rotation_norm,
    `Rheon.RigidMotion.rotation_pure,
    `Rheon.RigidMotion.rotation_sign_equivalence,
    `Rheon.RigidMotion.drift_displacement,
    `Rheon.RigidMotion.positive_clock,
    `Rheon.RigidMotion.kick_drift_constant_force_error,
    `Rheon.RigidMotion.scale,
    `Rheon.RigidMotion.totalAngular,
    `Rheon.RigidMotion.orbital_free_drift,
    `Rheon.RigidMotion.endpoint_angular_increment,
    `Rheon.RigidMotion.conditional_total_angular_impulse,
    `Rheon.SphereInterval.squared_nonnegative,
    `Rheon.SphereInterval.squared_cauchy,
    `Rheon.SphereInterval.convex_support,
    `Rheon.SphereInterval.departure_endpoint,
    `Rheon.SphereInterval.supported_distance,
    `Rheon.SphereInterval.departure_free_flight,
    `Rheon.SphereInterval.ledger,
    `Rheon.SphereInterval.ledger_sum,
    `Rheon.SphereInterval.conditional_ledger_nonincrease,
    `Rheon.SphereInterval.completion_requires_all_time]
  for name in expected do
    let _ ← getConstInfo name
    pure ()
  let mut audited := 0
  let mut auditedNames : Array Name := #[]
  for (name, info) in env.constants.toList do
    let isProofOrAxiom := match info with
      | .thmInfo _ => true
      | .axiomInfo _ => true
      | _ => false
    if name.toString.startsWith "Rheon." && (isProofOrAxiom || expected.contains name) then
      let axioms ← Lean.collectAxioms name
      for axiomName in axioms do
        unless allowed.contains axiomName do
          throwError "Disallowed axiom {axiomName} in {name}"
      logInfo m!"AUDITED {name}: {axioms}"
      audited := audited + 1
      auditedNames := auditedNames.push name
  for name in expected do
    unless auditedNames.contains name do
      throwError "Expected declaration not audited: {name}"
  logInfo m!"Axiom audit passed for {audited} declarations"
